const tinhThanh = [
    "Hà Nội",
    "TP. Hồ Chí Minh",
    "Đà Nẵng",
    "Hải Phòng",
    "Bắc Ninh",
    "Nam Định",
    "Nghệ An",
    "Thanh Hóa",
    "Quảng Ninh",
    "Quảng Bình",
    "Quảng Trị",
    "Thừa Thiên Huế",
    "Đồng Nai",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Phú Yên",
    "Kiên Giang",
    "An Giang",
    "Cần Thơ",
    "Lâm Đồng",
    "Vũng Tàu",
    "Hải Dương",
    "Thái Bình",
    "Hưng Yên",
    "Thái Nguyên",
    "Lạng Sơn",
    "Phú Thọ",
    "Yên Bái",
    "Tuyên Quang",
    "Lai Châu",
    "Điện Biên",
    "Sơn La",
    "Bắc Giang",
    "Lào Cai",
    "Tây Ninh",
    "Bà Rịa - Vũng Tàu",
    "Long An",
    "Tiền Giang",
    "Bến Tre",
    "Trà Vinh",
    "Vĩnh Long",
    "Đồng Tháp",
    "An Giang",
    "Kiên Giang",
    "Cà Mau",
  ];

  export default tinhThanh;